export default [
  {
    path: '/system',
    name: '系统管理',
    icon: 'setting',
    routes: [
      {
        path: '/system/user',
        name: '用户管理',
        icon: 'user',
        component: './system/user',
      },
      {
        path: '/system/role',
        name: '角色管理',
        icon: 'idcard',
        component: './system/role',
      },
      {
        path: '/system/menu',
        name: '菜单管理',
        icon: 'menu',
        component: './system/menu',
      },
      {
        path: '/system/cache',
        name: '缓存管理',
        icon: 'book',
        component: './system/cache',
      },
      {
        path: '/system/log/consumerLog',
        name: '消费者操作日志',
        icon: 'inbox',
        component: './system/log/consumerLog',
      },
      {
        path: '/system/log/systemLog',
        name: '系统操作日志',
        icon: 'inbox',
        component: './system/log/systemLog',
      },
    ],
  },
  {
    path: '/equipment',
    name: '设备管理',
    icon: 'crown',
    routes: [
      {
        path: '/equipment/add',
        name: '新增设备',
        icon: 'smile',
        component: './equipment/add',
      },
      {
        path: '/equipment/batteryRep',
        name: '电池健康报表',
        icon: 'smile',
        component: './equipment/batteryRep',
      },
      {
        path: '/equipment/battery',
        name: '电池管理',
        icon: 'smile',
        component: './equipment/battery',
      },
      {
        path: '/equipment/cabinet',
        name: '电柜管理',
        icon: 'smile',
        component: './equipment/cabinet',
      },
    ],
  },

  {
    path: '/iotManager',
    name: 'IOT管理',
    icon: 'icon-crown',
    routes: [
      {
        path: '/iotManager/cabinetManage',
        name: '电柜管理',
        icon: 'smile',
        component: './iotManager/cabinetManage', //authority: ['admin'],
      },
      {
        path: '/iotManager/batteryManage',
        name: '电池管理',
        icon: 'smile',
        component: './iotManager/batteryManage', //authority: ['admin'],
      },
      {
        path: '/iotManager/importDevice',
        name: '导入设备',
        icon: 'smile',
        component: './iotManager/importDevice', //authority: ['admin'],
      },
      {
        path: '/iotManager/iotLogs',
        name: 'IOT日志',
        icon: 'smile',
        component: './iotManager/iotLogs', //authority: ['admin'],
      },
      {
        path: '/iotManager/packageUpdate',
        name: '设备升级包管理',
        icon: 'smile',
        component: './iotManager/packageUpdate', //authority: ['admin'],
      },
      {
        path: '/iotManager/updateResult',
        name: '升级结果',
        icon: 'smile',
        component: './iotManager/updateResult', //authority: ['admin'],
      },
      {
        path: '/iotManager/equipmentUpdate',
        name: '设备升级',
        icon: 'smile',
        component: './iotManager/equipmentUpdate', //authority: ['admin'],
      },
      {
        path: '/iotManager/batteryMap',
        name: '电池GPS',
        icon: 'smile',
        component: './iotManager/batteryMap', //authority: ['admin'],
      },
    ],
  },
  {
    path: '/devOps',
    name: '运维管理',
    icon: 'crown',
    routes: [
      {
        path: '/devOps/faultHistory',
        name: '故障记录',
        icon: 'smile',
        component: './devOps/faultHistory',
      },
      {
        path: '/devOps/installHistory',
        name: '安装记录',
        icon: 'smile',
        component: './devOps/installHistory',
      },
      {
        path: '/devOps/log',
        name: '运维日志',
        icon: 'smile',
        component: './devOps/log',
      },
      {
        path: '/devOps/batteryOwnershipHistory',
        name: '电池归属历史查询',
        icon: 'smile',
        component: './devOps/batteryOwnershipHistory',
      },
      {
        path: '/devOps/udpLog',
        name: 'UDP上报日志',
        icon: 'smile',
        component: './devOps/udpLog',
      },
    ],
  },
  {
    path: '/merchant',
    name: '商户管理',
    icon: 'crown',
    routes: [
      {
        path: '/merchant/merchant',
        name: '商户信息',
        icon: 'smile',
        component: './merchant/merchant',
      },
      {
        path: '/merchant/orgUser',
        name: '员工管理',
        icon: 'icon-team',
        component: './merchant/orgUser',
      },
      {
        path: '/merchant/serviceOutlet',
        name: '服务网点',
        icon: 'smile',
        component: './merchant/serviceOutlet',
      },
      {
        path: '/merchant/merchantRole',
        name: '角色管理',
        icon: 'smile',
        component: './merchant/merchantRole',
      },
      {
        path: '/merchant/deposit',
        name: '押金模式',
        icon: 'smile',
        component: './merchant/deposit',
      },
      {
        path: '/merchant/package',
        name: '套餐管理',
        icon: 'smile',
        component: './merchant/package',
      },
      {
        path: '/merchant/group',
        name: '群组管理',
        icon: 'smile',
        component: './merchant/group',
      },
      {
        path: '/merchant/substitute',
        name: '代缴管理',
        icon: 'smile',
        component: './merchant/substitute',
      },
      {
        path: '/merchant/equipconfig',
        name: '设备参数设置',
        icon: 'smile',
        component: './merchant/equipconfig',
      },
      {
        path: '/merchant/generalizedQRCode',
        name: '推广二维码',
        icon: 'smile',
        component: './merchant/generalizedQRCode',
      },
      {
        path: '/merchant/cabinetbind',
        name: '电柜关系绑定',
        icon: 'smile',
        component: './merchant/cabinetbind',
      },
      {
        path: '/merchant/cabinetSearch',
        name: '柜效查询',
        icon: 'smile',
        component: './merchant/cabinetSearch',
      }
    ],
  },
  {
    path: '/channel',
    name: '渠道管理',
    icon: 'crown',
    routes: [
      {
        path: '/channel/channelList',
        name: '合作渠道',
        icon: 'smile',
        component: './channel/channelList',
      },
      {
        path: '/channel/examineList',
        name: '加入审核',
        icon: 'smile',
        component: './channel/examineList',
      },
    ],
  },
  {
    path: '/consumers',
    name: '骑手管理',
    icon: 'crown',
    routes: [
      {
        path: '/consumers/consumer',
        name: '用户列表',
        icon: 'smile',
        component: './consumers/consumer',
      },
      {
        path: '/consumers/feedback',
        name: '用户反馈',
        icon: 'smile',
        component: './consumers/feedback',
      },
      {
        path: '/consumers/coupon',
        name: '用户优惠券管理',
        icon: 'smile',
        component: './consumers/coupon',
      },
      {
        path: '/consumers/rightTransfer',
        name: '用户权益转移',
        icon: 'smile',
        component: './consumers/rightTransfer',
      },
      {
        path: '/consumers/refund',
        name: '退押金申请管理',
        icon: 'smile',
        component: './consumers/refund',
      },
      {
        path: '/consumers/smsLog',
        name: '短信发送记录',
        icon: 'smile',
        component: './consumers/smsLog',
      },
      {
        path: '/consumers/changePhoneLog',
        name: '手机号换绑记录',
        icon: 'icon-phone-fill',
        component: './consumers/changePhoneLog',
      },
      {
        path: '/consumers/qrBindingBatteryLog',
        name: '新用户领电池记录',
        icon: 'icon-folder',
        component: './consumers/qrBindingBatteryLog',
      },
      {
        path: '/consumers/realNameLog',
        name: '实名认证记录',
        icon: 'icon-filesearch',
        component: './consumers/realNameLog',
      },
    ],
  },
  {
    path: '/order',
    name: '订单管理',
    icon: 'setting',
    routes: [
      {
        name: '支付流水',
        icon: 'smile',
        path: '/order/payTradeLog',
        component: './order/payTradeLog',
      },
      {
        name: '套餐订单',
        icon: 'smile',
        path: '/order/payOrder',
        component: './order/payOrder',
      },
      {
        name: '押金订单',
        icon: 'smile',
        path: '/order/depositOrder',
        component: './order/depositOrder',
      },
      {
        name: '换电记录',
        icon: 'smile',
        path: '/order/exchange',
        component: './order/exchange',
      },
    ],
  },
  {
    path: '/finance',
    name: '财务管理',
    icon: 'crown',
    routes: [
      {
        path: '/finance/package',
        name: '套餐收入',
        icon: 'smile',
        component: './finance/package', //authority: ['admin'],
      },
      {
        path: '/finance/deposit',
        name: '押金流水',
        icon: 'smile',
        component: './finance/deposit', //authority: ['admin'],
      },
      {
        path: '/finance/withdraw',
        name: '提现记录',
        icon: 'smile',
        component: './finance/withdraw', //authority: ['admin'],
      },
      {
        path: '/finance/substitute',
        name: '代缴提现记录',
        icon: 'smile',
        component: './finance/substitute', //authority: ['admin'],
      },
    ],
  },
  {
    path: '/cabinetRep',
    name: '电柜报表',
    icon: 'crown',
    routes: [
      {
        path: '/cabinetRep/cabinetRepDay',
        name: '电柜日报',
        icon: 'smile',
        component: './cabinetRep/cabinetRepDay',
      },
      {
        path: '/cabinetRep/cabinetRepMonth',
        name: '电柜月报',
        icon: 'smile',
        component: './cabinetRep/cabinetRepMonth',
      },
    ],
  },
];
